### ISSUE TITLE
How can i calcalate accuracy?

### ISSUE THREAD

**Issue by kyunghoyu** [clip-italian/clip-italian#21]
Hello!
Thank you very much your work. I have one question. 
In  [train-CLIP](https://github.com/Zasder3/train-CLIP/blob/main/models/wrapper.py), it was possible to check the accuracy during training to evaluate the model's performance. How can i measure the accuracy during training in CLIP-italian?

**Comment by vinid** [comment]
Hello!

It might require a bit of work to edit the code to support that.

+ [Here](https://github.com/clip-italian/clip-italian/blob/master/hybrid_clip/run_hybrid_clip.py#L791) you can see an example of how to get data at validation time.

+ [The call to the model](https://github.com/clip-italian/clip-italian/blob/master/hybrid_clip/modeling_hybrid_clip.py#L121) already returns the image and text embeddings so you can extract these and then use a script similar to the one in train clip.

Albeit, I am not sure this will work since we had some compatibility issues recently with this jax implementation

**Comment by kyunghoyu** [comment]
Hello!
Thank you for your response. I appreciate your guidance and I will make an effort to try the method you provided using the code available online.
